defaults: &defaults
  language:                       'th-TH'
  platform:                       'avaya'
  redis_server:                   'localhost'
  redis_server_port:              6379
  audio_prompt_path:              '/prompts/'
  grammar_path:                   '/grammars/'
  enable_tuning_tools:            false
  tuning_tools_site:              'http://localhost:3000'
  log_path:                       '/var/aminets/log/virtual_agent_compact_app'
  log_level:                      'info'
  enable_log_in_vxml:             true
  log_http_method:                'get'
  is_a_part_of_call_flow:         false
  mmivr_enable:                   false
  gvp_extension_enable:           false
  say_command:                    /usr/bin/say
  sox_command:                    /usr/local/bin/sox
  use_server_time:                true
  keep_vxml:                      false
  enable_prompt_log:              false
  use_json:                       true
  next_main_enabled:              true
  session_expire_sec:             86400
  enable_prompt_uploader:         false
  enable_dialog_console:          false
  dialog_console_filename:        config/dialog.yml
  max_retry:                      2
  confirm_intention_always:       false
  
  ### confirmation_option "always", "never", "confidence_base"
  dialog_property:
    main_menu_dialog:
      reset_initial_variable:
        is_reset:                            true
        retry:                               0
        reject:                              0
        timeout:                             0
      max_retry:                             2
      max_reject:                            2
      max_timeout:                           2
      confirmation_option:                   'never'
      confirmation_confidence_threshold:     0.1
      prompts:
        init:                                [['welcome']]
        retry:                               [['sorry_ask_for_service_with_short_sentence']]
        reject:                              [['sorry_ask_for_service_with_short_sentence']]
        timeout:                             [['sorry_ask_for_service_with_short_sentence']]
    ask_for_product_dialog:
      reset_initial_variable:
        is_reset:                            false
        retry:                               0
        reject:                              0
        timeout:                             0
      max_retry:                             2
      max_reject:                            2
      max_timeout:                           2
      confirmation_option:                   'never'
      confirmation_confidence_threshold:     0.1
      prompts:
        init:                                [['want_to_receive_service', 'ask_product']]
        retry:                               [['sorry_can_you_say_again']]
        reject:                              [['sorry_can_you_say_again']]
        timeout:                             [['sorry_can_you_say_again']]
        confirm:                             [['is_it_correct']]
    ask_for_intent_dialog:
      reset_initial_variable:
        is_reset:                            false
        retry:                               0
        reject:                              0
        timeout:                             0
      max_retry:                             2
      max_reject:                            2
      max_timeout:                           2
      confirmation_option:                   'never'
      confirmation_confidence_threshold:     0.1
      prompts:
        init:                                [['ask_intention']]
        retry:                               [['sorry_ask_for_service_again']]
        reject:                              [['sorry_ask_for_service_again']]
        timeout:                             [['sorry_ask_for_service_again']]
        confirm:                             [['is_it_correct']]
    confirm_intent_dialog:
      max_retry:                             2
      confirmation_option:                   'never'
      confirmation_confidence_threshold:     0.1
      prompts:
        init:                                [['you_contact_intention', 'of_product', 'if_yes_please_wait']]
        retry:                               []
        reject:                              []
        timeout:                             []
    confirm_intent_to_agent_dialog:
      max_retry:                             2
      confirmation_option:                   'never'
      confirmation_confidence_threshold:     0.1
      prompts:
        init:                                [['transfer_to_agent_for_service', 'of_product', 'if_yes_please_wait']]
        retry:                               []
        reject:                              []
        timeout:                             []

test:
  <<: *defaults
  log_level:                      'fatal'
  log_path:                       'log/amivoice_dialog_module'

development:
  <<: *defaults
  log_path:                       'log/amivoice_dialog_module'

production:
  <<: *defaults
